<?php
/* This file was automatically generated by the `grunt libs:cachebuster` command (Fri Sep 03 2021 14:22:35 GMT+1000 (Australian Eastern Standard Time)). */
return array(
	'mobx' => '4.15.4',
	'react' => '16.13.1',
	'react-dom' => '16.13.1'
);
